
```{r load_libraries}

library(tidyverse)

library(tidymodels)

```

```{r load_data}

penguin_data = read_csv(here::here("data", "palmer_penguins_data.csv"))

```


```{r fit_linear_reg}

preprocess_recipe = recipe(bill_depth_mm ~ .,
                           data = penguin_data) %>% 
  step_dummy(species) %>% 
  step_interact(terms = ~starts_with("species"):body_mass_g)


model_spec = linear_reg()


linear_model_workflow = workflow() %>% 
  add_recipe(preprocess_recipe) %>% 
  add_model(model_spec) %>% 
  fit(penguin_data)


```


```{r fit_linear_reg_one_hot, eval=FALSE}

preprocess_recipe = recipe(bill_depth_mm ~ .,
                    data = penguin_data) %>% 
  step_dummy(species, one_hot = TRUE) %>% 
  step_interact(terms = ~starts_with("species"):body_mass_g)



model_spec = linear_reg() %>% 
  set_engine("lm")


linear_model_workflow = workflow() %>% 
  add_recipe(preprocess_recipe) %>% 
  add_model(model_spec,
            formula = bill_depth_mm ~ 0 + . -body_mass_g) %>% 
  fit(penguin_data)


```


```{r coefficients}

linear_model_workflow %>% 
  tidy()

```

```{r predict}

predictions = linear_model_workflow %>% 
  predict(penguin_data)



```

```{r plot}

penguin_data %>% 
  bind_cols(predictions) %>% 
  pivot_longer(-c(body_mass_g, species),
               names_to = "obs_type") %>% 
  ggplot(aes(body_mass_g, y = value, color = obs_type)) + 
  geom_point()

```

