
```{r load_libraries}

library(tidyverse)

library(tidymodels)

```

```{r load_data}

penguin_data = read_csv(here::here("data", "palmer_penguins_data.csv"))

penguin_data = penguin_data %>% 
  select(-species) %>% 
  distinct()

```

```{r define_specs}

preproc_rec = recipe(bill_depth_mm ~ body_mass_g, data = penguin_data)

knn_spec = nearest_neighbor(mode = "regression",neighbors = tune())

cv_folds = vfold_cv(penguin_data,5)

param_grid = grid_regular(neighbors(range = c(1, 220)), levels = 100)

knn_workflow = workflow() %>% 
  add_recipe(preproc_rec) %>% 
  add_model(knn_spec)

```

```{r tune_results}

tune_results =  knn_workflow %>% 
  tune_grid(resamples = cv_folds,grid = param_grid)

```

```{r plot_metrics}

tune_results %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(neighbors, mean)) + 
  geom_point()

```


```{r select_best_model}

best_params = tune_results %>% 
  select_best(metric = "rmse")

```


```{r predict}

temp = knn_workflow %>% 
  finalize_workflow(best_params) %>% 
  fit(penguin_data) %>% 
  last_fit(split = initial_split(penguin_data))




predictions = knn_model_fit %>% 
  predict(penguin_data)

penguin_data %>% 
  select(bill_depth_mm, body_mass_g) %>% 
  bind_cols(predictions) %>% 
  pivot_longer(-body_mass_g) %>% 
  ggplot(aes(body_mass_g, y = value, color = name)) + 
  geom_point()

```

